name: flow_2019_11

dependencies:
    - python==3.6.8
    - scipy==1.1.0
    - lxml==4.4.1
    - six==1.11.0
    - path.py
    - python-dateutil==2.7.3
    - tensorflow==1.9.0 # should it be 1.10.0?
    - cloudpickle==1.2.1
    #- opencv # do I need it? I added it in the past from some reason
    - setuptools==41.0.0
    - pip:
        - gym==0.14.0
        - pyprind==2.11.2
        - nose2==0.8.0
        - cached_property
        - joblib==0.10.3
        - matplotlib==3.0.0
        - dill
        - lz4
        - ray==0.8.5
        - setproctitle
        - psutil
        - opencv-python
        - boto3==1.4.8
        - redis~=2.10.6
        - git+https://github.com/Theano/Theano.git@adfe319ce6b781083d8dc3200fb4481b00853791#egg=Theano
        - git+https://github.com/neocxi/Lasagne.git@484866cf8b38d878e92d521be445968531646bb8#egg=Lasagne
        - plotly==3.2.0
